# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildNodeApp
    steps:    
    - script: |
        echo "XXXXXXXXXXXXXXXXXXX"
        pwd
        ls -ltrh      
        cd NodejsWebApp1
        pwd
        echo "XXXXXXXXXXXXXXXXXXX"
      displayName: show path
    - task: UseNode@1
      inputs:
        version: '6.x'
    - bash: |    
        cd $(System.DefaultWorkingDirectory)/NodejsWebApp1/
        npm install 
      displayName: install npm
    - task: Gulp@1
      inputs:
        gulpFile: '$(System.DefaultWorkingDirectory)/NodejsWebApp1/gulpfile.js'
        targets: 
        enableCodeCoverage: false
    - task: Npm@0
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)/NodejsWebApp1/'
        command: 'test'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/NodejsWebApp1'
        artifact: 'app_binary'
        publishLocation: 'pipeline'  
      