# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildNodeApp
    steps:    
    - script: |
        echo "XXXXXXXXXXXXXXXXXXX"
        pwd
        ls -ltrh      
        cd NodejsWebApp1
        pwd
        echo "XXXXXXXXXXXXXXXXXXX"
    - script: |
        cd $(System.DefaultWorkingDirectory)/NodejsWebApp1/
        npm install 
#    - task: Npm@1
#      inputs:
#        command: 'install'
#        workingDir: '$(System.DefaultWorkingDirectory)/NodejsWebApp1/package.json'
#    - script: echo Hello, world!
#      displayName: 'Run a one-line script'
